### ISSUE TITLE
Problem with S1C timezone

### ISSUE THREAD

**Issue by jcwlim** [nitaybz/homebridge-broadlink-s1c#6]
Hi, I have a timezone error. It crash my homebridge very frequent. Can't figure out what is the problem.
Below is the log that I get.

  EventedHTTPServer [::ffff:192.168.1.180] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.180] HTTP request: /characteristics?id=1.15 +8ms
  HAPServer [7F:0F:8F:4A:7F:79] HAP Request: GET /characteristics?id=1.15 +1ms
  Accessory [Windows] Getting value for Characteristic "Streaming Status" +2ms
  Accessory [Windows] Got Characteristic "Streaming Status" value: AQEA +0ms
  EventedHTTPServer [::ffff:192.168.1.180] HTTP Response is finished +2ms
/usr/lib/node_modules/homebridge-broadlink-s1c/node_modules/broadlinkjs-s1c/index.js:139
            packet[0x08] = timezone;
                       ^

Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (crypto.js:160:26)
    at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-s1c/node_modules/broadlinkjs-s1c/index.js:235:27)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:544:8)
root@mediahub:~/.homebridge# nano config.json
root@mediahub:~/.homebridge# cp config.json config.jsonv2.8

**Comment by nitaybz** [comment]
It seems like there are 2 issues in this log.
what I've learned so far is that this error happens when there are other Broadlink devices in the network or other broadlink plugins installed on the same machine.
Please let me know what is the situation in your house so I can better understand the issue.

regarding the second issue, uninstalling and installing the plugin again should solve the problem. I did some change in the broadlinkjs-s1c library and you should see that it installs the 0.1.1 version.

I hope this will at least prevent crashing homebridge.

**Comment by jcwlim** [comment]
You are right, I have more than 1 plugin install in the same machine.
there are homebridge-broadlink-rm, -platform, -s1c
I also have more than 1 broadlink devices in the network.
Do you know how to resolve this?

**Comment by nitaybz** [comment]
the fix I did should prevent this issue from appearing on my plugin... it could show again on other plugins as well though.
there are 2 ways to fix that... first one is to install each plugin on a different machine, that way, no conflicts will be between them.

second option is to edit the code:
the fix is to go to each plugin code, look for the broadlinkjs library (under homebridge-broadlink-.../node_modules, for example:
broadlinkjs-sm for homebridge-broadlink-platform
broadlinkjs-rm for homebridge-broadlink-rm.

in each library you should edit the index file. search for `var p2 = decipher.final();` and replace with:
```
try{
   var p2 = decipher.final();
} catch (e){}
```

this is a workaround to prevent homebridge from crashing... found it very helpful...

**Comment by jcwlim** [comment]
Thanks for the response.
Yes, I did that at another 2 plugins that I installed. Since yesterday until now, there are no crash at the moment. but somehow, my plugin become not responsive. All just show "updating......" I still figure out how to keep the homebridge refresh..

**Comment by nitaybz** [comment]
try installing my version for [homebridge-broadlink-platform](https://github.com/nitaybz/homebridge-broadlink-platform)

it's much easier on the system and might prevent the situation you're having

**Comment by jcwlim** [comment]
Yes, I do installed your broadlink-platform. But I still need broadlink-rm for my RM Pro.
After I apply a try catch to "p2", the s1c plugin crash with other message now.
I am trying to obtain the message to you.

**Comment by jcwlim** [comment]
I got the error message.
Oct 18 16:09:09 mediahub homebridge[289]: events.js:163
Oct 18 16:09:09 mediahub homebridge[289]: throw er; // Unhandled 'error' event
Oct 18 16:09:09 mediahub homebridge[289]: ^
Oct 18 16:09:09 mediahub homebridge[289]: Error: bind EMFILE 0.0.0.0
Oct 18 16:09:09 mediahub homebridge[289]: at Object.exports._errnoException (util.js:1050:11)
Oct 18 16:09:09 mediahub homebridge[289]: at exports._exceptionWithHostPort (util.js:1073:20)
Oct 18 16:09:09 mediahub homebridge[289]: at _handle.lookup (dgram.js:215:18)
Oct 18 16:09:09 mediahub homebridge[289]: at _combinedTickCallback (internal/process/next_tick.js:83:11)
Oct 18 16:09:09 mediahub homebridge[289]: at process._tickCallback (internal/process/next_tick.js:104:9)
Oct 18 16:09:09 mediahub systemd[1]: secure1.service: main process exited, code=exited, status=1/FAILURE

**Comment by nitaybz** [comment]
please install the latest version...

**Comment by nitaybz** [comment]
did you check the latest version? I want to close ticket because I'm not experiencing this issue anymore...

**Comment by nitaybz** [comment]
closing
